/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gpu_matrix_Initializer */

#ifndef _Included_gpu_matrix_Initializer
#define _Included_gpu_matrix_Initializer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gpu_matrix_Initializer
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gpu_matrix_Initializer_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
