/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gpu_matrix_Vector */

#ifndef _Included_gpu_matrix_Vector
#define _Included_gpu_matrix_Vector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gpu_matrix_Vector
 * Method:    axpy
 * Signature: (DLgpu/matrix/Vector;)Lgpu/matrix/Vector;
 */
JNIEXPORT jobject JNICALL Java_gpu_matrix_Vector_axpy
  (JNIEnv *, jobject, jdouble, jobject);

/*
 * Class:     gpu_matrix_Vector
 * Method:    scal
 * Signature: (D)Lgpu/matrix/Vector;
 */
JNIEXPORT jobject JNICALL Java_gpu_matrix_Vector_scal
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     gpu_matrix_Vector
 * Method:    clone
 * Signature: ()Lgpu/matrix/Vector;
 */
JNIEXPORT jobject JNICALL Java_gpu_matrix_Vector_clone
  (JNIEnv *, jobject);

/*
 * Class:     gpu_matrix_Vector
 * Method:    dot
 * Signature: (Lgpu/matrix/Vector;)D
 */
JNIEXPORT jdouble JNICALL Java_gpu_matrix_Vector_dot
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gpu_matrix_Vector
 * Method:    nrm2
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_gpu_matrix_Vector_nrm2
  (JNIEnv *, jobject);

/*
 * Class:     gpu_matrix_Vector
 * Method:    asum
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_gpu_matrix_Vector_asum
  (JNIEnv *, jobject);

/*
 * Class:     gpu_matrix_Vector
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gpu_matrix_Vector_print
  (JNIEnv *, jobject);

/*
 * Class:     gpu_matrix_Vector
 * Method:    newInstance
 * Signature: ([D)Lgpu/matrix/Vector;
 */
JNIEXPORT jobject JNICALL Java_gpu_matrix_Vector_newInstance
  (JNIEnv *, jclass, jdoubleArray);

/*
 * Class:     gpu_matrix_Vector
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gpu_matrix_Vector_finalize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
