#!/usr/bin/env bash

cd "$(dirname ${BASH_SOURCE[0]})"
cd ../src/java

if [ "$#" = "2" ]; then
    echo "Creating javah file";
else
    echo "expecting <class name> <output file>";
    exit 1;
fi;

pwd;

KLASS=$1;
OUTFILE=$2;
JAVA_SOURCE_FILE=`perl -e '$_=shift; s/\./\//g;print "$_.java";' $KLASS`

javac -cp ../../target/classes:. $JAVA_SOURCE_FILE; 
javah -o "../native/$2" "$1"
